const express = require('express');
var router = express.Router();

// //routes for user table of database
var user=require('../api/user.js');
var condition = require('../api/condition.js');
var physicalIssues = require('../api/physicalIssues.js');
var advert = require('../api/advertisement.js');
var mobile = require('../api/mobile.js');
var payment = require('../api/payment.js');
var packages = require('../api/package.js');
var paypal = require('../api/paypal.js');
var chat = require('../api/chat.js');
router.post('/placeAdd',advert.placeAdd);
router.post('/getUserDetails',user.getUserDetails);
router.post('/uploadImage/:id',physicalIssues.uploadImageAdvert);
router.post('/phoneIssues',physicalIssues.phoneIssues);
router.post('/getAllPhysicalIssues/:id',physicalIssues.getAllPhysicalIssues);
router.post('/phoneSwitchOn',advert.phoneSwitchOn);
router.post('/advertisementHistory',advert.advertisementHistory);
router.post('/verifyTrue',advert.verifyTrue);
router.post('/makeOffer',advert.makeOffer);
router.post('/acceptRejectOffer',advert.acceptRejectOffer);
router.post('/myAdds',advert.myAdds);
router.post('/selfCreatedOffers',advert.selfCreatedOffers);
router.post('/updateAddLocation',advert.updateAddLocation);
//router.post('/uploadImageAdvert',physicalIssues.uploadImageAdvert);
router.post('/addIssuesAccessories',physicalIssues.addIssuesAccessories);
router.post('/getAllConditions',condition.getAllConditions);
router.post('/addCondition',condition.addCondition);
router.post('/createMobileBrand',mobile.createMobileBrand);
router.post('/updateUser',user.updateUser);
router.post('/checkMobile',user.checkMobile);
router.post('/uploadUserImage',user.uploadUserImage);
router.post('/addNewUserDetails',payment.addNewUserDetails);
router.post('/addUserCard',payment.addUserCard);
router.post('/retreiveCustomerCards',payment.retreiveCustomerCards);
router.post('/makePaymentWithCard',payment.makePaymentWithCard);
router.post('/getFavouriteAdds',user.getFavouriteAdds);
router.post('/addFavouriteAdds',user.addFavouriteAdds);
router.post('/boostAdverisement',advert.boostAdverisement);
router.post('/getAllPackages',packages.getAllPackages);
router.post('/updateUserPackage', packages.updateUserPackage);
router.post('/changePassword',user.changePassword1);
router.post('/deleteCard',payment.deleteCard);
router.post('/updateDefaultCard',payment.updateDefaultCard);
router.post('/getAllChats',chat.getAllChats);
router.post('/getAllMessages',chat.getAllMessages);
router.post('/deleteImage',advert.deleteImage);
router.post('/enableDisableAdd',advert.enableDisableAdd);
router.post('/placeAddWeb',advert.placeAddWeb);
router.post('/getAdvertisementDetails',advert.getAdvertisementDetails);
router.post('/getMyAddsOffers',advert.getMyAddsOffers);
router.post('/removeMyCreatedOffer',advert.removeMyCreatedOffer);
router.post('/getAllOffersCreatedBySelf',advert.getAllOffersCreatedBySelf);
router.post('/updateOfferCreatedBySelf',advert.updateOfferCreatedBySelf);
router.post('/enterAddress',payment.enterAddress);
router.post('/addCourierInfo',payment.addCourierInfo);
router.post('/courierReceived',payment.courierReceived);
router.post('/myPurchases',advert.myPurchases);
router.post('/getSail',payment.getSail);
router.post('/boostsPurchased',user.boostsPurchased);
router.post('/report',advert.report);
router.post('/endBoost',advert.endBoost);
router.post('/createCounterOffer',advert.createCounterOffer);
router.post('/addImeiNumber',advert.addImeiNumber);
router.post('/acceptRejectCounterOffer',advert.acceptRejectCounterOffer);
router.post('/readUnreadOffers',advert.readUnreadOffers);
router.post('/getUnread',chat.getUnread);
router.post('/removePaypal',user.removePaypal);
router.post('/deleteAdvertisement',advert.deleteAdvertisement);
router.post('/paypalCreatePayment',paypal.paypalCreatePayment);
router.post('/cancelDeal',advert.cancelDeal);
router.post('/getSingleAdsOffers',advert.getSingleAdsOffers);
router.post('/deleteChat',chat.deleteChat);
router.post('/repostAdvertisement',advert.repostAdvertisement);
router.post('/getAllReports',advert.getAllReports);
router.post('/getAlPendinglReports',advert.getAlPendinglReports);
router.post('/viewAllAdvertisements', advert.viewAllAdvertisements);
router.post('/enableDisableAddAdmin',advert.enableDisableAddAdmin);
router.post('/adminActionReport',advert.adminActionReport);
router.post('/getAllUsers',user.getAllUsers);
router.post('/getAllSuspendedUsers',user.getAllSuspendedUsers);
router.post('/suspendUser',user.suspendUser);
router.post('/unsuspendUser',user.unsuspendUser);
router.post('/unsuspendAllUsers',user.unsuspendAllUsers);
router.post("/makeAdmin",user.makeAdmin);
module.exports = router;
