var mongoose = require('mongoose');
var MobileSchema = new mongoose.Schema({
  DeviceName: {type:String , unique:true},
        Brand: {type: mongoose.Schema.Types.ObjectId, ref: 'MobileBrand'},
        technology: {type:String},
        gprs: {type:String},
        edge: {type:String},
        announced: {type:String},
        status: {type:String},
        dimensions: {type:String},
        weight: {type:String},
        sim: {type:String},
        type: {type:String},
        resolution: {type:String},
        card_slot: {type:String},
        phonebook: {type:String},
        camera_c: {type:String},
        alert_types: {type:String},
        loudspeaker_: {type:String},
        wlan: {type:String},
        bluetooth: {type:String},
        gps: {type:String},
        radio: {type:String},
        messaging: {type:String},
        length:{type:Number},
        width:{type:Number},
        clock: {type:String},
        alarm: {type:String},
        games: {type:String},
        java: {type:String},
        battery_c: {type:String},
        stand_by: {type:String},
        talk_time: {type:String},
        _2g_bands: {type:String} ,
        _3_5mm_jack_: {type:String},
        pictures:{type:Array},
        featured:{type:Boolean},
        offers:{type:Array},
        screenDiagonal:{type:Number,select: false}
});
module.exports = mongoose.model('Mobile',MobileSchema);
